src/apps/newsletters/urls.py
from django.conf.urls import url
from .views_ajax import AddNewsletter, SendNewsletter


app_name = 'newsletters'
urlpatterns = [
    url(r'^popups/add/$', AddNewsletter.as_view(), name='popup_add'),
    url(r'^send/$', SendNewsletter.as_view(), name='send'),
]

src/apps/subscribers/urls.py
from django.conf.urls import url
# from . import views_ajax


# app_name = 'subscribers'
# urlpatterns = [
#     url(r'^thank-you/$', views_ajax.SuccessView.as_view(), name='success'),
# ]

src/settings/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from main.views import MainPageView


urlpatterns = [
    url('admin/', admin.site.urls),
    # url('^django_rq/', include('django_rq.urls')),
    url('newsletters/', include('newsletters.urls', namespace='newsletters')),
    # url('mailer/', include('mailer.urls', namespace='main')),
    url('', MainPageView.as_view()),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.STATIC_ROOT)

src/apps/main/models.py
from django.utils.translation import ugettext_lazy as _, ugettext
from solo.models import SingletonModel

class MainPageConfig(SingletonModel):
    
    class Meta:
        default_permissions = ('change', )
        verbose_name = _('settings')

    def __str__(self):
        return ugettext('Main page')

src/apps/newsletters/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _, ugettext
from django.conf import settings
from subscribers.models import Subscriber


class Newsletter(models.Model):
    title = models.CharField(_("title"), blank=False, max_length=128,)
    text = models.TextField(_("text"), blank=False)
    subscribers = models.ManyToManyField(Subscriber, verbose_name=_("subscribers"), blank=False)
    sended = models.BooleanField(_("Sended"), default=False)
    date_sended = models.DateTimeField(_("date sended"), blank=True, null=True)
    count_opened = models.PositiveSmallIntegerField(_('count opened'), default=0)

    class Meta:
        ordering=("title", )
        verbose_name = _('newsletter')
        verbose_name_plural = _('newsletters')

    def __str__(self):
        return self.title
    
    @property
    def status(self):
        return "Sended {}".format(self.date_sended) if self.sended else _("Not sended")
    
    @property
    def register_link(self):
        return "{}?newsletter_id={}".format(reverse('newsletter:register'), self.id)

src/apps/subscribers/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Subscriber(models.Model):
    first_name = models.CharField(_("first name"), max_length=64, )
    last_name = models.CharField(_("last name"), max_length=64, )
    date_birth = models.DateField(_("date birth"), null=True, blank=True, )
    email = models.EmailField(_("email"), unique=True)

    class Meta:
        ordering=("first_name", "last_name", )
        verbose_name = _('subscriber')
        verbose_name_plural = _('subscribers')

    @property
    def fullname(self):
        return "{} {}".format(self.first_name, self.last_name)
    
    def __str__(self):
        return self.fullname

src/apps/newsletters/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import EmailValidator
import re
from datetime import datetime
from .models import Newsletter
from subscribers.models import Subscriber


class NewsletterForm(forms.ModelForm):
    postponed = forms.BooleanField(
        label=_("postponed"),
        required=False
    )

    for_all_subscribers = forms.BooleanField(
        label=_("for all subscribers"),
        required=False
    )
    
    subscribers = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Subscriber.objects.all(),
    )
    
    class Meta:
        model = Newsletter
        fields = '__all__'
        exclude = ['sended', 'date_sended', 'count_opened']

src/apps/subscribers/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import EmailValidator
from .models import Subscriber
import re
from datetime import datetime


class ContactForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(attrs={
                'placeholder': _('John'),
            }),
            'last_name': forms.TextInput(attrs={
                'placeholder': _('Doe'),
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': _('john@gmail.com'),
            }),
            'date_birth': forms.DateField(),
        }
        error_messages = {
            'first_name': {
                'required': _('Please enter first name'),
                'max_length': _('First name should not be longer than %(limit_value)d characters'),
                'min_length': _("The first name is very short"),
            },
            'last_name': {
                'required': _('Please enter last name'),
                'max_length': _('Last name should not be longer than %(limit_value)d characters'),
                'min_length': _("The last name is very short"),
            },
            'email': {
                'required': _('Please enter e-mail'),
                'incorrect': _("E-mail is incorrect"),

            },
            'data_birth': {
                'incorrect': _('Date of birth can\'t be more now'),

            },
        }

    def clean_first_name(self):
        if 'first_name' in self.cleaned_data:
            first_name = self.cleaned_data.get('first_name')

            if not first_name:
                self.add_field_error('first_name', 'required')
            else:

                if len(first_name) < 3:
                    self.add_field_error('first_name', 'min_length')

            return name

    def clean_last_name(self):
        if 'last_name' in self.cleaned_data:
            last_name = self.cleaned_data.get('last_name')

            if not last_name:
                self.add_field_error('last_name', 'required')
            else:

                if len(last_name) < 3:
                    self.add_field_error('last_name', 'min_length')

            return last_name

    def clean_email(self):
        if 'email' in self.cleaned_data:
            email = self.cleaned_data.get('email')

            if not email:
                self.add_field_error('email', 'required')
            else:
                r = re.findall(r'[а-яА-я]', email)

                if len(r) > 0:
                    self.add_field_error('email', 'incorrect')
                else:
                    self.cleaned_data['email'] = email

            return email

    def clean_date_birth(self):
        if 'date_birth' in self.cleaned_data:
            date_birth = self.cleaned_data.get('date_birth')

            if date_birth and date_birth > datetime.now():
                self.add_field_error('date_birth', 'incorrect')
            return date_birth

src/apps/main/views.py
from django.template import loader
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.template import RequestContext
from .models import MainPageConfig
from newsletters.models import Newsletter


class MainPageView(TemplateView):
    template_name = 'main/index.html'

    def get(self, request, *args, **kwargs):
        config = MainPageConfig.get_solo()
        newslettters = Newsletter.objects.all().order_by('-sended')

        return self.render_to_response({
            'page': config,
            'newsletters': newslettters,
        },  )

src/apps/main/templates/main/index.html
{% extends "layout.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div class="container">

<div class="actions">
    <button id="addNewsletter" class="btn btn-primary">Add Newesletter</button>
</div>

<form action="" id="newsletters">
    {% csrf_token %}
    <table class="table">
    <thead>
        <tr>
        <th scope="col">{% trans 'Title' %}</th>
        <th scope="col">{% trans 'Status' %}</th>
        <th scope="col">{% trans 'Count opened' %}</th>
        <th scope="col">{% trans 'Actions' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for newsletter in newsletters %}
        <tr>
            <td>{{ newsletter.title }}</td>
            <td>{{ newsletter.status }}</td>
            <td>{{ newsletter.count_opened }}</td>
            <td>{% if not newsletter.sended %}<button type="button" class="btn btn-primary btn-send" data-newsletter="{{ newsletter.id }}">{% endif %} {% trans 'Send' %}</button></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</form>

{% endblock content %}

src/apps/newsletters/templates/newsletters/popups/add.html
{% load bootstrap3 %}


<form action="{% url 'newsletters:popup_add' %}" method="post" id="fmAddNewsletter" >
  {% csrf_token %}
  {% bootstrap_form form exclude='subscribers, for_all_subscribers, postponed' %}
  {% bootstrap_form form exclude='title, text, postponed, subscribers' %}
  {% bootstrap_form form exclude='title, text, postponed, for_all_subscribers' %}
  {% bootstrap_form form exclude='title, text, subscribers, for_all_subscribers' %}
  <input type="submit" class="btn btn-success"  value="Submit">
</form>

src/templates/components/popup.html
<div id="popup" class="modal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close">x</button>
        </div>
        <div class="modal-body">
          <p>Modal body text goes here.</p>
        </div>
      </div>
    </div>
  </div>

src/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head lang="en">
        <title>Mailer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">    

        <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}/>
        <link rel="stylesheet" href={% static "css/popups.css" %}/>
    </head>
    <body>
        {% block content %}{% endblock content %}
        {% include "components/popup.html" %}
        <script src={% static "js/jquery-3.6.3.min.js" %}></script>
        <script src={% static "js/bootstrap.bundle.min.js" %}></script>
        <script src={% static "main/js/popups.js" %}></script>
        <script src={% static "main/js/mails.js" %}></script>
        <script src={% static "newsletters/js/forms.js" %}></script>
    </body>
</html>